### ISSUE TITLE
How to set a password?

### ISSUE THREAD

**Issue by babam86** [lonetwin/sftpserver#5]
How to set a password on the server?

Thanks.

**Comment by lonetwin** [comment]
> How to set a password on the server?
> 
> Thanks.

The stub implementation does not provide any authentication methods. You may choose any authentication scheme you prefer by implementing the appropriate methods of the [StubServer](https://github.com/lonetwin/sftpserver/blob/92f47e1d1281cbe018727787bfc353ede6814367/src/sftpserver/stub_sftp.py#L27-L42) class. For example, in the simplest scheme of a username/password based auth, you might do something like:

```python

class StubServer (ServerInterface):
    def check_auth_password(self, username, password):
        if (username, password) in [('admin', 'sup3rSk3r3t')]:
            return AUTH_SUCCESSFUL
        return AUTH_FAILED

    def get_allowed_auths(self, username):
        """List availble auth mechanisms."""
        return "password"

```
