### ISSUE TITLE
Certain directories are not accessible/its contents are empty.

### ISSUE THREAD

**Issue by babam86** [lonetwin/sftpserver#6]
Distro: Porteus 5.0/Slackware 15.0 

```
sudo sftpserver --host 192.168.xxx.xxx -p 2222 -r /
```

The `/etc` directory is empty on the client.

```
guest@porteus:~/SFTPMount/root@192.168.xxx.xxx:2222 $ ls ./etc
ls: reading directory './etc': No such file or directory
guest@porteus:~/SFTPMount/root@192.168.xxx.xxx:2222 $ ls ./etc/*
ls: cannot access './etc/*': No such file or directory
guest@porteus:~/SFTPMount/root@192.168.xxx.xxx:2222 $ ls ./etc/xdg/
Thunar  autostart  libfm  menus  openbox  pcmanfm  tumbler  user-dirs.conf  user-dirs.defaults  xfce4
guest@porteus:~/SFTPMount/root@192.168.xxx.xxx:2222 $ ls ./etc/fuse.conf
./etc/fuse.conf
guest@porteus:~/SFTPMount/root@192.168.xxx.xxx:2222 $
```

That's very strange, why is the `/etc` directory unreadable?

Thanks.

**Comment by babam86** [comment]
If a directory contains broken symlinks then the client cannot read it.

```
# mkdir /var/test
# ln -s nonexistent /var/test/
# sftpserver --host IPADDRESS -p PORT -r /var
```

Then the `/var/test` directory is not readable by the client.

Is this a bug in `sftpserver` or `paramiko`?

**Comment by lonetwin** [comment]
@babam86 thanks for reporting the issue. This appears to be a problem in `sftpserver`, specifically in the `list_folder()` implementation of the `StubSFTPServer` implementation. I'll attempt to add a fix for this sometime today. OTOH, PRs are welcome as well.

**Comment by lonetwin** [comment]
@babam86 could you please try out the change in PR #7 and confirm whether that fixes the issue in your environment ?

**Comment by babam86** [comment]
@lonetwin Yes, it works.

Thanks.
